// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestDevWebService.Models;

namespace TestDevWebService.Migrations
{
    [DbContext(typeof(TestWebAppContext))]
    [Migration("20200902203843_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestDevWebService.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<string>("Game")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<int>("IdUser");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<int>("Quantity");

                    b.HasKey("IdItem");

                    b.HasIndex("IdUser");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("TestDevWebService.Models.Property", b =>
                {
                    b.Property<int>("IdProperty")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdItem");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("Value")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.HasKey("IdProperty");

                    b.HasIndex("IdItem");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("TestDevWebService.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.HasKey("IdUser");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasName("UC_Name");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TestDevWebService.Models.Item", b =>
                {
                    b.HasOne("TestDevWebService.Models.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TestDevWebService.Models.Property", b =>
                {
                    b.HasOne("TestDevWebService.Models.Item", "Item")
                        .WithMany("Properties")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
